In [2]:
import numpy as np

In [3]:
l=([1,2,3,4,5,6,7])
a1=np.arange(5)
a2=np.arange(1,5)
a3=np.arange(1,5,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4]
[1 2 3 4]
[1 3]


In [4]:
#Linspace
b1=np.linspace(1,11,3,retstep=True)
print(b1)
b2=np.linspace(1,10,4,retstep=True,endpoint=True)
print(b2)

(array([ 1.,  6., 11.]), np.float64(5.0))
(array([ 1.,  4.,  7., 10.]), np.float64(3.0))


In [5]:
#Zeros
print(np.zeros((2,)))
print(np.zeros((2,3)))
print(np.zeros((2,3,4)))


[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [6]:
#ones
print(np.ones((2,)))
print(np.ones((2,3,4)))
print(np.ones((2,3,4)))

#outer=2,inner=3,val=4

[1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
#Full
print(np.full((2,3),7))
print(np.full((2,5),(5)))
#outer=2,inner values=3, perticular value to print=7

[[7 7 7]
 [7 7 7]]
[[5 5 5 5 5]
 [5 5 5 5 5]]


In [8]:
#eye
#identity matrix will come
print(np.eye(3))
print(np.eye(3,4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
