In [1]:
import numpy as np

In [2]:
np.array(10)


array(10)

In [3]:
a1=np.array(10)
print(a1)
print(a1.ndim)

10
0


In [4]:
a2=np.array(10.5)
print(a2)
print(a2.ndim)

10.5
0


In [5]:
a3=np.array("sasi")
print(a3)
print(a3.ndim)

sasi
0


In [6]:
a4=np.array(2+10j)
print(a4)
print(a4.ndim)

(2+10j)
0


In [7]:
a5=np.array(2+10j)
print(a5.dtype)

complex128


In [8]:
l=[10,20,30,40,50]
np.array(l)

array([10, 20, 30, 40, 50])

In [9]:
a6=np.array(l)
print(a6)
print(a6.ndim)
print(a6.dtype)
print(a6.size)

[10 20 30 40 50]
1
int64
5


In [10]:
l1=[10,15.9,10]
a=np.array(l1)
print(a)
print(a.dtype)

[10.  15.9 10. ]
float64


In [11]:
l2=[2+3j,4+2j]
b=np.array(l2)
print(b)
print(b.dtype)

[2.+3.j 4.+2.j]
complex128


In [12]:
l3="sasisivasal"
c=np.array(l3)
print(c)
print(c.dtype)

sasisivasal
<U11


In [13]:
l4=[10,2.5,2+3j,"sasi"]
c=np.array(l4)
print(c)
print(c.dtype)


['10' '2.5' '(2+3j)' 'sasi']
<U64


In [14]:
l5=[True,False]
c=np.array(l5)
print(c)
print(c.dtype)

[ True False]
bool


In [15]:
d=np.array([20,500])
print(d)
print(d.dtype)#int having only 8 bytes 
print(d.itemsize)#64/8
print(d.size)
print(d.nbytes)# 8*2
print(d.shape)# how many elements present inthe list that len will come with coma(,)  and tuple formate

[ 20 500]
int64
8
2
16
(2,)


In [16]:
d=np.array([20,500,55],dtype=np.int32)
print(d)
print(d.dtype)
print(d.itemsize)# individual size 32/8=4
print(d.size)
print(d.nbytes)#complete array 4*3=12

[ 20 500  55]
int32
4
3
12


In [17]:
l7=[[10,20],[30,40],[50,60]]
e=np.array(l7)
print(e)
print(e.ndim)#2dim
print(e.size)#len of the list
print(e.shape)#3 maens outer elements,2 means inner elements
print(e.itemsize)#int having 8 bytes
print(e.nbytes)#

[[10 20]
 [30 40]
 [50 60]]
2
6
(3, 2)
8
48


In [19]:
l8=[[[1,2],[3,4],[5.6],[7,8]]]
f=np.array(l8)
print(f)
print(f.ndim)
print(f.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.