In [2]:
import numpy as np

In [ ]:
i=np.array([10,20,30,40,50])
print(i[0])
print(i[-1])


10
50


In [ ]:
i=np.array([[10,20,30],[40,50,60]])
print(i[0])
print(i[0,1])
print(i[-1,-1])

[10 20 30]
20
60


In [10]:
s=[10,20,30,40,50]
print(s[::])
print(s[0:3:])
print(s[0::2])


[10, 20, 30, 40, 50]
[10, 20, 30]
[10, 30, 50]


In [19]:
mdim=np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(mdim[::2,::2])
print(mdim[0,::-1])
print(mdim[::,1])

[[10 30]
 [70 90]]
[30 20 10]
[ 20  50  80 110]


In [38]:
m=np.array([[[10,20,30],[40,50,60]],#0(0,1)
            [[70,80,90],[11,12,13]]])#1(0,1)
print(m[::,0,0])
print(m[::-1,::-1,-1])
print(m[::,::,0])# [10 11] not possible
print(m[::-1,1::,-1])

[10 70]
[[13 90]
 [60 30]]
[[10 40]
 [70 11]]
[[13]
 [60]]
