In [87]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [94]:
print(np.zeros((2,3,4)))
print(np.ones((2,3)))
print(np.eye(4))
print(np.full((2,3), 5))
print(np.arange(0,10,2))

import random as rd
# print(rd.randint(1,10,5))
m = np.random.randint(1,10,(3,3))
print(m)
print(np.random.rand(3))
print(np.random.choice(arr,size=3,replace=True))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5 5 5]
 [5 5 5]]
[0 2 4 6 8]
[[3 8 9]
 [6 3 4]
 [1 1 3]]
[0.62544476 0.02204857 0.742943  ]
[2 1 4]


In [ ]:
# array properties
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print( arr.dtype)

(2, 3, 3)
3
18
int64


In [ ]:
#indeximg amd  slicing
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr2)
print(arr2[1:2,0:2,1:3])
print(arr2[0:2,0:3,1:2])
print(arr2[0:2,0:3,0:1])
print(arr2[0:2,0:3,2:3])#[block,row,column]
print(arr2[:1,1:3,2:3])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[11 12]
  [14 15]]]
[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]]
[[[ 1]
  [ 4]
  [ 7]]

 [[10]
  [13]
  [16]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]]
[[[6]
  [9]]]


In [ ]:
# Mathematical Operations
print(arr2**2)
print(arr2+4)
print(arr2*3)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]]
[[[ 5  6  7]
  [ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]
  [20 21 22]]]
[[[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[30 33 36]
  [39 42 45]
  [48 51 54]]]


In [ ]:
#Statistical Operations
print(arr2.sum())
print(arr2.mean())
print(np.median(arr2))
print(arr2.min())
print(arr2.max())
print(arr2.std())


171
9.5
9.5
1
18
5.188127472091127


In [ ]:
#Matrix Oerations
print(arr+arr)
print(arr2*arr2)
print(arr2.T)
print(arr2.transpose(1,0,2))

[ 2  4  6  8 10]
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]]
[[[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]

 [[ 3 12]
  [ 6 15]
  [ 9 18]]]
[[[ 1  2  3]
  [10 11 12]]

 [[ 4  5  6]
  [13 14 15]]

 [[ 7  8  9]
  [16 17 18]]]


In [ ]:
#Reshaping Arrays
print(arr2.reshape(9,2))
print(arr2.reshape(2,9))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [ ]:
#Flattening
print(arr2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [ ]:
#Broadcasting
print(arr2+10)

[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]


In [ ]:
#Copy vs View
print(arr2.copy())
print(arr2.view())

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
#Stacking Arrays
print(np.hstack((arr,arr)))
print(np.vstack((arr,arr)))

[1 2 3 4 5 1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
#Filtering
print(arr2[arr2>0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
