In [18]:
import numpy as np
import numpy.random as rd

In [19]:
const=2
a=np.arange(1,9)
b=a+const
c=a-const
d=a*const
e=a%const
f=a/const
g=a//const
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

[ 3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6]
[ 2  4  6  8 10 12 14 16]
[1 0 1 0 1 0 1 0]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[0 1 1 2 2 3 3 4]


In [20]:
const=5
a=np.arange(1,9)
b=(a==const).any()# if u r giving  any () atleast one element will satisfy it will gives true otherwise false
c=(a!=const).any()
d=(a<const).all()#if u r giving  all ()   all element will satisfy it will gives true otherwise false
e=a>const
f=a<=const
g=a>=const
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
h=a[a>const]# true elements are returned
print(h)
i=(a>const)

True
True
False
[False False False False False  True  True  True]
[ True  True  True  True  True False False False]
[False False False False  True  True  True  True]
[6 7 8]


In [21]:
a2=np.array([2,4,7])
const=3
print(a2&const)#0010 & 0011 = 0010 = 2,0100 & 0011 = 0000 = 0,0111 & 0011 = 0011 =3-----> both the conditions true
print(a2|const) # atleast one condition true
print(a2^const)# same conditions is there it will gives true
print(a2<<const)#[16 32 56]
print(a2>>const)#[0 0 0]

[2 0 3]
[3 7 7]
[1 7 4]
[16 32 56]
[0 0 0]


In [ ]:
print((a<2) & (a<5))#[ True False False False False False False False]
print((a==2) | (a==5))#[False  True False False False False False  True]
print(~(a==5))#[ True False  True  True  True  True  True False]
print(a[~(a==5)])#[1 2 3 4 6 7 8]
print(a[(a<2) & (a<5)])#[1]
print(a[(a==2) | (a==5)])#[2 5]

[ True False False False False False False False]
[False  True False False  True False False False]
[ True  True  True  True False  True  True  True]
[1 2 3 4 6 7 8]
[1]
[2 5]


In [23]:
a1=a+2
print(a1)#[ 3  4  5  6  7  8  9 10]
a1+=10
a1

[ 3  4  5  6  7  8  9 10]


array([13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
#identity operator
a1=np.array([1,2,3])
a2=np.array([1,2,3])# it will stored in different memory 
a1 is a2#False


False

In [25]:
#membership operator
3 in a2 #True
5 in a1 #False

False

In [26]:
a1=np.arange(1,6)
print(a1)
a2=np.array([3,1,2,5,2])
print(a2)

[1 2 3 4 5]
[3 1 2 5 2]


In [27]:
#arthematic
print(a1 + a2 )
print(a1 - a2)
print(a1 * a2)
print(a1 % a2)
print(a1 / a2)
print(a1 // a2)

[4 3 5 9 7]
[-2  1  1 -1  3]
[ 3  2  6 20 10]
[1 0 1 4 1]
[0.33333333 2.         1.5        0.8        2.5       ]
[0 2 1 0 2]


In [28]:
#relational
print(a1 == a2 )
print(a1 != a2)
print(a1 < a2)
print(a1 > a2)
print(a1 <= a2)
print(a1 >= a2)


[False False False False False]
[ True  True  True  True  True]
[ True False False  True False]
[False  True  True False  True]
[ True False False  True False]
[False  True  True False  True]


In [29]:
#bitwise
print(a1 & a2 )
print(a1 | a2)
print(a1[~(a1 == a2)])


[1 0 2 4 0]
[3 3 3 5 7]
[1 2 3 4 5]


In [30]:
a1=np.array([1,2,3,4,5,6])
print(np.sqrt(a1))
print(np.power(a1,2))#a1 is base,2 is power exponential
print(np.exp(a1))
b=np.array([2.71828183 ,  7.3890561 ,  20.08553692,  54.59815003 ,148.4131591
, 403.42879349])
np.log(b)


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 1  4  9 16 25 36]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


array([1., 2., 3., 4., 5., 6.])

In [31]:
rd.seed(0)
a=rd.randint(20,50,10)
a

array([32, 35, 41, 20, 23, 47, 23, 27, 29, 39], dtype=int32)

In [32]:
print(len(a))
print(a.shape)


10
(10,)


In [43]:
print(np.reshape(a,(5,2)))
print(np.reshape(a,(5,2,1)))


[[32 35]
 [41 20]
 [23 47]
 [23 27]
 [29 39]]
[[[32]
  [35]]

 [[41]
  [20]]

 [[23]
  [47]]

 [[23]
  [27]]

 [[29]
  [39]]]


In [59]:
rd.seed(6)
a1=rd.randint(1,10,12)
print(a1)
print(np.reshape(a1,(4,3)))
print(np.reshape(a1,-1))

[4 5 1 2 2 5 2 9 3 5 3 6]
[[4 5 1]
 [2 2 5]
 [2 9 3]
 [5 3 6]]
[4 5 1 2 2 5 2 9 3 5 3 6]


In [ ]:
a2=np.array([[4, 5 ,1], [2, 2 ,5], [2 ,9, 3],[5 ,3, 6]])
print(a2.size)
a2

12


array([[4, 5, 1],
       [2, 2, 5],
       [2, 9, 3],
       [5, 3, 6]])

In [74]:
x=np.ravel(a2)
x

array([4, 5, 1, 2, 2, 5, 2, 9, 3, 5, 3, 6])

In [75]:
a2[0,0]=100
print(a2)
print(x)


[[100   5   1]
 [  2   2   5]
 [  2   9   3]
 [  5   3   6]]
[100   5   1   2   2   5   2   9   3   5   3   6]


In [77]:
a3=np.array([[2,3,4,5],[6,7,8,9],[1,2,3,4]])
print(a3.size)
print(a3)
y=a3.flatten()
print(y)
a3[0,0]=200
print(a3)
print(y)

12
[[2 3 4 5]
 [6 7 8 9]
 [1 2 3 4]]
[2 3 4 5 6 7 8 9 1 2 3 4]
[[200   3   4   5]
 [  6   7   8   9]
 [  1   2   3   4]]
[2 3 4 5 6 7 8 9 1 2 3 4]
