In [1]:
import numpy as np#this is for arrays methods

In [2]:
import numpy.random as rd# this is for random methods

In [3]:
import numpy as np
import numpy.random as rd

In [4]:
# print(rd.seed(0))# i will not change random
# print(rd.seed(3))#if u change the seed val ten it will chamge random values
print(rd.seed(1))
print(rd.randint(1,10,20))
print(rd.randint(100,1000,50))

None
[6 9 6 1 1 2 8 7 3 5 6 3 5 3 5 8 8 2 8 1]
[186 241 493 107 419 929 634 413 613 996 416 309 364 828 753 727 531 733
 556 642 171 487 554 661 413 615 892 597 143 688 126 920 436 721 983 397
 566 115 164 296 125 467 838 571 382 765 716 122 877 807]


In [ ]:
#it will give standerd  uniform distribution
print(rd.rand(5))
print(rd.rand(2,3))
print(rd.rand(2,3,2))

[0.61387109 0.32413853 0.45736018 0.44411711 0.82813536]
[[0.42634815 0.34569882 0.6749716 ]
 [0.22148206 0.46724582 0.31476569]]
[[[0.6268556  0.87736047]
  [0.447689   0.78445742]
  [0.4569657  0.65622933]]

 [[0.13184098 0.43298151]
  [0.90931199 0.605479  ]
  [0.76677459 0.50470061]]]


In [ ]:
a=rd.randn(5)
print(a,end='\n\n')
print(rd.mean(a))
print(rd.std( ))


In [ ]:
l=["red","blue","yelow","black","pink"]
print(rd.choice(l))
print(rd.choice(l,size=4))#duplicates is there
print(rd.choice(l,size=3,replace=False))#noduplicates
print(rd.choice(l,size=(2,3),replace=True))# duplicates possible

yelow
['blue' 'black' 'red' 'pink']
['red' 'blue' 'yelow']
[['red' 'yelow' 'yelow']
 ['blue' 'blue' 'pink']]


In [52]:
l=["red","blue","yelow","black","pink"]
print(rd.choice(l,size=3,p=[0.2,0.5,0.2,0.0,0.1]))

['blue' 'red' 'yelow']
