In [2]:
import numpy as np

In [3]:
a1=np.array([20,100,15,40,30,100,5,6])
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.mean(a1))#40+30/2=39.5
print(np.sum(a1)/a1.size)
print(np.sum(a1)/len(a1))
print(np.median(a1))# it will arrange in ascending order ofter it will give mean value
print((a1))
print(np.median(a1,overwrite_input=True))
print(a1)

100
5
316
39.5
39.5
39.5
25.0
[ 20 100  15  40  30 100   5   6]
25.0
[  5   6  15  20  30 100 100  40]


In [4]:
#percentile
a1=np.array([20,100,15,40,30,5,6])
print(np.median(a1,overwrite_input=True))
print(a1)
# which num 100% of the data is present
print(np.percentile(a1,100))
print(np.percentile(a1,50))#belo 100% of the data is present
print(np.percentile(a1,0))# below the 50% data is present
print(np.percentile(a1,2))# 2 is the percentage
print(a1)

20.0
[  5   6  15  20  30  40 100]
100.0
20.0
5.0
5.12
[  5   6  15  20  30  40 100]


In [ ]:
#var()
a2=np.array([2,5,3,1,4])# sales r in thousands
print(np.mean(a2))#revenue is around 3 thousand
# every day sales will be in <=3 and >=3 thousand
print(np.var(a2))#unit is in (thousand squere)---(not recommended for comparision)
print(np.std(a2))# on an avg 1.4 thousand deviation is present in the sales


3.0
2.0
1.4142135623730951
